"""Invariants of the schema itself.

These assert on the table *definitions*, not on a database that happens to have
been migrated already. A hand-written migration once dropped a constraint from
the database while the model kept declaring it; every behavioural test passed,
because they all ran against the migrated database, and the next autogenerated
migration quietly put the constraint back.
"""

from __future__ import annotations

import pytest

from app.connectors.postgres.tables import audit_events, identifications, metadata

#: Records of what happened must outlive what they describe, so they carry no
#: foreign keys into the data they refer to.
HISTORICAL_TABLES = ("audit_events", "identifications")


@pytest.mark.parametrize("table_name", HISTORICAL_TABLES)
def test_historical_records_have_no_foreign_keys(table_name: str) -> None:
    table = metadata.tables[table_name]
    assert table.foreign_keys == set(), (
        f"{table_name} must not reference other tables: a record of what happened "
        "has to survive the deletion of what it describes"
    )


def test_identifications_may_name_a_person_that_no_longer_exists() -> None:
    """The column stays, the constraint does not."""
    column = identifications.c.best_person_uuid
    assert column.nullable is True
    assert column.foreign_keys == set()


def test_audit_events_records_a_person_without_constraining_it() -> None:
    assert audit_events.c.person_uuid.foreign_keys == set()


def test_face_samples_cascade_from_their_person() -> None:
    """Erasing a person must take their biometric material with them."""
    table = metadata.tables["face_samples"]
    person = next(iter(table.c.person_uuid.foreign_keys))
    assert person.ondelete == "CASCADE"


def test_embeddings_cascade_from_their_sample() -> None:
    table = metadata.tables["face_embeddings"]
    sample = next(iter(table.c.face_sample_uuid.foreign_keys))
    assert sample.ondelete == "CASCADE"


def test_credentials_store_no_plaintext() -> None:
    """Neither table has anywhere to put a secret even by accident."""
    assert "token_sha256" in metadata.tables["api_tokens"].c
    assert "token" not in metadata.tables["api_tokens"].c
    assert "password_hash" in metadata.tables["users"].c
    assert "password" not in metadata.tables["users"].c


def test_language_vectors_are_attributed_to_model_provenance() -> None:
    table = metadata.tables["language_documents"]
    assert {"embedding_model", "embedding_version", "vector_collection"} <= set(table.c.keys())
    assert "normalized_text" in table.c


def test_processing_state_is_isolated_in_its_own_schema() -> None:
    assert {
        "processing.jobs",
        "processing.job_attempts",
        "processing.outbox_events",
        "processing.worker_heartbeats",
    } <= set(metadata.tables)


def test_processing_attempts_cascade_from_their_job() -> None:
    attempts = metadata.tables["processing.job_attempts"]
    job_uuid = next(iter(attempts.c.job_uuid.foreign_keys))
    assert job_uuid.ondelete == "CASCADE"


def test_processing_jobs_have_no_binary_column() -> None:
    jobs = metadata.tables["processing.jobs"]
    assert not {"image", "media", "embedding", "content"} & set(jobs.c.keys())
