"""Build a BlackGlass-compatible report from committed, cited evidence."""

from __future__ import annotations

from typing import Any

SECTIONS = [
    ("osp-cover-meta", "Report Details", "ރިޕޯޓްގެ ތަފްޞީލު"),
    ("osp-profile-summary", "Profile Summary", "ޕްރޮފައިލް ޚުލާސާ"),
    ("osp-key-findings", "Key Findings", "މުހިންމު ހޯދުންތައް"),
    ("osp-figure-photos", "Subject Images", "މައުޟޫޢުގެ ފޮޓޯ"),
    ("osp-identity-photo", "Identity & Photo Assessment", "ވަނަވަރާއި ފޮޓޯ އެސެސްމަންޓް"),
    ("osp-image-integrity", "Image Integrity & Manipulation Review", "ފޮޓޯގެ ސައްޙަކަން ބެލުން"),
    ("osp-platform-snapshot", "Platform Snapshot", "ޕްލެޓްފޯމް ޚުލާސާ"),
    ("osp-username-evolution", "Username & Identity Evolution", "ޔޫޒަރނޭމް ބަދަލުވި ގޮތް"),
    ("osp-public-info", "Publicly Identifiable Information", "ޢާންމުކޮށް ފެންނަ މަޢުމާތު"),
    ("osp-figure-behaviour", "Observed Behavioural Tendencies", "ފެންނަ އުޅުމުގެ ސިފަތައް"),
    ("osp-behaviour-pattern", "Behavioural Pattern", "އުޅުމުގެ ސިފަ"),
    ("osp-routines", "Daily Routines & Habits", "ދުވަހީ އާދަތައް"),
    ("osp-communication-style", "Communication Style", "މުޢާމަލާތުކުރާ ގޮތް"),
    ("osp-decision-risk", "Decision-Making & Risk", "ނިންމުންތަކާއި ނުރައްކާ"),
    ("osp-triggers", "Emotional & Contextual Triggers", "އަސަރުކުރާ ކަންތައްތައް"),
    ("osp-privacy-contradictions", "Privacy Contradictions", "ޕްރައިވަސީ ފުށުއެރުން"),
    ("osp-behaviour-timeline", "Behaviour Change Timeline", "އުޅުން ބަދަލުވި ތާރީޚް"),
    ("osp-analytical-cautions", "Analytical Cautions", "ސަމާލުކަންދޭންވީ ކަންތައް"),
    ("osp-figure-associates", "Subject and Close Associates", "މައުޟޫޢާއި ގާތް ފަރާތްތައް"),
    ("osp-associates", "Associates & Online Circles", "ގުޅުންހުރި ފަރާތްތަކާއި ސާރކަލްތައް"),
    ("osp-associate-detail", "Associate — Name & Role", "ގުޅުންހުރި ފަރާތް"),
    ("osp-interpreting-association", "Interpreting Association", "ގުޅުން މާނަކުރުން"),
    ("osp-data-exposure", "Data-Exposure Record", "މަޢުލޫމާތު ބޭޒާރުވުން"),
    ("osp-risky-behaviour", "Risky or Negligent Security Behaviour", "ސެކިއުރިޓީގައި އިހުމާލު"),
    ("osp-crypto-footprint", "Cryptocurrency Footprint", "ކްރިޕްޓޯ ފުޓްޕްރިންޓް"),
    ("osp-screening", "Suspicious-Activity Screening", "ޝައްކުކުރެވޭ ޙަރަކާތް ބެލުން"),
    ("osp-indicators-not-found", "Serious Indicators Checked but Not Found", "ބެލި ނަމަވެސް ނުފެނުނު ކަންތައް"),
    ("osp-integrated-profile", "Integrated Profile", "ޖުމްލަ ޕްރޮފައިލް"),
    ("osp-confidence-gaps", "Confidence & Gaps", "ޔަޤީންކަމާއި ފަޅުކަން"),
    ("osp-photo-catalogue", "Photo Catalogue & Visual-Evidence Log", "ފޮޓޯ ލޮގު"),
    ("osp-platform-matrix", "Selected Platform Matrix", "ޕްލެޓްފޯމް މެޓްރިކްސް"),
]


def localized(en: str, dv: str = "") -> dict[str, str]:
    """Return the localized-cell shape used by BlackGlass report exports."""
    return {"en": en, "dv": dv}


def build_blackglass_report(analysis: dict[str, Any]) -> dict[str, Any]:
    """Create a deterministic report; never add conclusions absent from the result."""
    source = analysis["source"]
    evidence = analysis.get("evidence", [])
    findings = analysis.get("findings", [])
    contradictions = analysis.get("contradictions", [])
    warnings = analysis.get("warnings", [])
    analysis_id = str(analysis["analysis_id"])
    generated_at = analysis["updated_at"].isoformat()
    evidence_refs = [
        {
            "evidenceId": str(item["evidence_id"]),
            "kind": item["kind"],
            "quote": item["original_text"],
            "locator": item["locator"],
            "provenance": item["provenance"],
            "reviewStatus": item.get("review_status", "unreviewed"),
        }
        for item in evidence
    ]
    by_section: dict[str, list[dict[str, Any]]] = {}
    for item in findings + contradictions:
        by_section.setdefault(item.get("section", "osp-key-findings"), []).append(item)
    gaps = [f"{item['stage']}: {item['code']}" for item in warnings]
    unsupported = "Insufficient cited evidence for a supported conclusion."
    blocks = []
    for index, (kind, en, dv) in enumerate(SECTIONS, start=1):
        body = unsupported
        rows: list[list[dict[str, str]]] = []
        if kind == "osp-cover-meta":
            body = "Cyber-ai evidence analysis report. Findings remain unreviewed."
            rows = [
                [localized("Analysis ID"), localized(analysis_id)],
                [localized("Source system"), localized(source["system"])],
                [localized("Source record"), localized(source["object_id"])],
                [localized("Status"), localized(analysis["status"])],
            ]
        elif kind in by_section:
            body = "Post-derived, cited observations generated by cyber-ai."
            rows = [
                [
                    localized(item["statement"]),
                    localized(f"Confidence: {item.get('confidence', 0.5):.2f}"),
                    localized(item.get("basis", "explicit")),
                    localized(
                        ", ".join(str(citation["evidence_id"]) for citation in item["citations"])
                    ),
                ]
                for item in by_section[kind]
            ]
        elif kind == "osp-analytical-cautions":
            body = "Citations establish source linkage, not factual truth or semantic entailment."
            rows = [[localized(gap)] for gap in gaps]
        elif kind == "osp-confidence-gaps":
            body = "Unreviewed output; inspect retained originals before relying on conclusions."
            rows = [[localized(gap)] for gap in gaps] or [[localized(unsupported)]]
        elif kind == "osp-photo-catalogue":
            visual = [item for item in evidence if item["kind"] == "visual_observation"]
            body = "Sampled visual observations; unsampled content is not represented."
            rows = [
                [localized(str(item["evidence_id"])), localized(item["original_text"])]
                for item in visual
            ]
        blocks.append(
            {
                "id": f"{analysis_id}-{index}",
                "type": kind,
                "heading": localized(en, dv),
                "body": localized(body),
                "rows": rows,
            }
        )
    outline = [
        {
            "id": block["id"],
            "blockKey": block["type"],
            "kind": "section",
            "title": block["heading"],
            "enabled": True,
            "collapsed": False,
            "status": "ready",
        }
        for block in blocks
    ]
    machine_findings = [{**item, "kind": "finding"} for item in findings] + [
        {**item, "kind": "contradiction"} for item in contradictions
    ]
    return {
        "message": "Report generated successfully.",
        "data": {
            "id": analysis_id,
            "reference": f"EE/{analysis_id[:8]}",
            "reference_prefix": "EE",
            "reference_serial": analysis_id[:8],
            "reference_year": analysis["updated_at"].year,
            "subject": source["object_id"],
            "subject_id": source["object_id"],
            "subject_type": source["object_type"],
            "lang": "en",
            "status": "draft",
            "generation_status": "ready"
            if analysis["status"] in {"completed", "partial"}
            else analysis["status"],
            "last_error": None,
            "version": analysis["revision"],
            "template": "eagleeye-evidence-v1",
            "template_version": "1.0",
            "created_at": analysis["created_at"].isoformat(),
            "updated_at": generated_at,
            "generated_at": generated_at,
            "created_by_id": "cyber-ai",
            "metadata": {
                "content_items": len(evidence),
                "linked_profiles": 0,
                "gaps": gaps,
                "subject_platform": source["system"],
                "observation_from": source.get("collected_at"),
                "observation_to": source.get("collected_at"),
                "cover_profile_image_url": None,
                "generation_options": {"citation_required": True},
                "generator": {"system": "cyber-ai", "pipeline": "evidence_analysis"},
            },
            "document": {
                "schema": 2,
                "version": {"stage": "draft", "number": "0.1"},
                "lang": "en",
                "cover": {
                    "date": generated_at,
                    "focus": source["object_type"],
                    "purpose": "Evidence analysis",
                    "subject": source["object_id"],
                    "version": str(analysis["revision"]),
                    "profileImage": "",
                    "observationFrom": source.get("collected_at"),
                    "observationTo": source.get("collected_at"),
                },
                "outline": outline,
                "content": {"lexical": {"root": {"type": "root", "children": []}}},
                "evidenceRefs": evidence_refs,
                "mediaRefs": [],
                "findings": machine_findings,
            },
            "blocks": blocks,
        },
    }
