"""identifications and audit log

Revision ID: 35141621313d
Revises: dcece6ee12f6
Create Date: 2026-08-19 00:38:02.427576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "35141621313d"
down_revision: Union[str, Sequence[str], None] = "dcece6ee12f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("audit_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_identifier", sa.String(length=256), nullable=False),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("person_uuid", sa.UUID(), nullable=True),
        sa.Column("face_sample_uuid", sa.UUID(), nullable=True),
        sa.Column("identification_uuid", sa.UUID(), nullable=True),
        sa.Column("policy_version", sa.String(length=128), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("actor_kind IN ('user', 'system')", name="ck_audit_actor_kind"),
        sa.PrimaryKeyConstraint("audit_uuid"),
        comment="Append-only record of administrative and review actions.",
    )
    op.create_index(
        "ix_audit_events_identification", "audit_events", ["identification_uuid"], unique=False
    )
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"], unique=False)
    op.create_index("ix_audit_events_person", "audit_events", ["person_uuid"], unique=False)
    op.create_table(
        "identifications",
        sa.Column("identification_uuid", sa.UUID(), nullable=False),
        sa.Column("query_sha256", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("accept_at", sa.Float(), nullable=False),
        sa.Column("review_at", sa.Float(), nullable=False),
        sa.Column("best_person_uuid", sa.UUID(), nullable=True),
        sa.Column("best_score", sa.Float(), nullable=True),
        sa.Column(
            "candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("review_outcome", sa.String(length=16), nullable=True),
        sa.Column("reviewed_by", sa.String(length=256), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('accept', 'review', 'reject')", name="ck_identification_outcome"
        ),
        sa.CheckConstraint(
            "review_outcome IS NULL OR review_outcome IN ('confirmed', 'rejected')",
            name="ck_identification_review_outcome",
        ),
        sa.ForeignKeyConstraint(["best_person_uuid"], ["persons.person_uuid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("identification_uuid"),
        comment="Identification attempts, with the decision and the policy that produced it.",
    )
    op.create_index("ix_identifications_outcome", "identifications", ["outcome"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_identifications_outcome", table_name="identifications")
    op.drop_table("identifications")
    op.drop_index("ix_audit_events_person", table_name="audit_events")
    op.drop_index("ix_audit_events_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_identification", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
