"""person, external identifiers and face samples

Revision ID: 5e5780ed997c
Revises:
Create Date: 2026-08-18 14:04:04.740161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e5780ed997c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("person_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("person_uuid"),
        comment="People. person_uuid is the sole internal key.",
    )
    op.create_table(
        "face_samples",
        sa.Column("face_sample_uuid", sa.UUID(), nullable=False),
        sa.Column("person_uuid", sa.UUID(), nullable=False),
        sa.Column("image_sha256", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("image_sha256 ~ '^[0-9a-f]{64}$'", name="ck_face_sample_sha256"),
        sa.ForeignKeyConstraint(["person_uuid"], ["persons.person_uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("face_sample_uuid"),
        sa.UniqueConstraint("person_uuid", "image_sha256", name="uq_face_sample_person_content"),
        comment="Face captures. A person has many; no sample is privileged over another.",
    )
    op.create_index("ix_face_samples_person", "face_samples", ["person_uuid"], unique=False)
    op.create_table(
        "person_external_identifiers",
        sa.Column("person_uuid", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('id', 'local_id')", name="ck_external_identifier_kind"),
        sa.ForeignKeyConstraint(["person_uuid"], ["persons.person_uuid"], ondelete="CASCADE"),
        sa.UniqueConstraint("source", "kind", "value", name="uq_external_identifier_scope"),
        comment="Upstream identifiers (id, local_id) as source-scoped attributes of a person.",
    )
    op.create_index(
        "ix_external_identifiers_person",
        "person_external_identifiers",
        ["person_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_external_identifiers_person", table_name="person_external_identifiers")
    op.drop_table("person_external_identifiers")
    op.drop_index("ix_face_samples_person", table_name="face_samples")
    op.drop_table("face_samples")
    op.drop_table("persons")
    # ### end Alembic commands ###
