"""token expiry

Revision ID: 6904bc245c44
Revises: a1e093fc7216
Create Date: 2026-08-19 11:07:43.846316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6904bc245c44"
down_revision: Union[str, Sequence[str], None] = "a1e093fc7216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_tokens", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_tokens", "expires_at")
    # ### end Alembic commands ###
