"""api tokens

Revision ID: a1e093fc7216
Revises: 35141621313d
Create Date: 2026-08-19 10:31:30.038876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1e093fc7216"
down_revision: Union[str, Sequence[str], None] = "35141621313d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("token_uuid", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("token_sha256", sa.String(length=64), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('user', 'service')", name="ck_api_token_kind"),
        sa.PrimaryKeyConstraint("token_uuid"),
        sa.UniqueConstraint("token_sha256"),
        comment="API credentials. Secrets are never stored, only their SHA-256.",
    )
    op.create_index("ix_api_tokens_subject", "api_tokens", ["subject"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_api_tokens_subject", table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
