"""password accounts

Revision ID: b09c07269569
Revises: cde2c7d24322
Create Date: 2026-08-19 15:34:28.367792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b09c07269569"
down_revision: Union[str, Sequence[str], None] = "cde2c7d24322"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_uuid"),
        sa.UniqueConstraint("email"),
        comment="Password accounts. Signing in mints a short-lived api_tokens row.",
    )
    op.add_column("api_tokens", sa.Column("user_uuid", sa.UUID(), nullable=True))
    # Autogenerate proposed re-creating identifications_best_person_uuid_fkey
    # here: the model had drifted and still declared it, though revision
    # cde2c7d24322 had already dropped it from the database on purpose. The
    # model is corrected; nothing to do to the schema.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_tokens", "user_uuid")
    op.drop_table("users")
    # ### end Alembic commands ###
