"""face embedding metadata

Revision ID: b8265d112b06
Revises: 5e5780ed997c
Create Date: 2026-08-18 15:36:45.088632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8265d112b06"
down_revision: Union[str, Sequence[str], None] = "5e5780ed997c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "face_embeddings",
        sa.Column("embedding_uuid", sa.UUID(), nullable=False),
        sa.Column("face_sample_uuid", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("preprocessing_version", sa.String(length=128), nullable=False),
        sa.Column("vector_collection", sa.String(length=255), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("dimension > 0", name="ck_face_embedding_dimension"),
        sa.ForeignKeyConstraint(
            ["face_sample_uuid"], ["face_samples.face_sample_uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("embedding_uuid"),
        sa.UniqueConstraint(
            "face_sample_uuid",
            "model_name",
            "model_version",
            "preprocessing_version",
            name="uq_face_embedding_sample_provenance",
        ),
        comment="Metadata for embeddings held in the vector store. The vectors themselves live in Qdrant; this table records what produced them.",
    )
    op.create_index(
        "ix_face_embeddings_collection", "face_embeddings", ["vector_collection"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_face_embeddings_collection", table_name="face_embeddings")
    op.drop_table("face_embeddings")
    # ### end Alembic commands ###
