"""face sample processing state

Revision ID: dcece6ee12f6
Revises: b8265d112b06
Create Date: 2026-08-18 21:07:17.420519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcece6ee12f6"
down_revision: Union[str, Sequence[str], None] = "b8265d112b06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "face_samples",
        sa.Column(
            "processing_state",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
    )
    op.add_column(
        "face_samples", sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("face_samples", sa.Column("failure_reason", sa.Text(), nullable=True))
    op.create_index(
        "ix_face_samples_processing_state", "face_samples", ["processing_state"], unique=False
    )
    op.create_check_constraint(
        "ck_face_sample_processing_state",
        "face_samples",
        "processing_state IN ('pending', 'processed', 'failed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_face_sample_processing_state", "face_samples", type_="check")
    op.drop_index("ix_face_samples_processing_state", table_name="face_samples")
    op.drop_column("face_samples", "failure_reason")
    op.drop_column("face_samples", "processed_at")
    op.drop_column("face_samples", "processing_state")
    # ### end Alembic commands ###
